AllCops:
  Excludes:
    - Guardfile
    - Rakefile
    - grape-slate.gemspec
    - vendor/**/*
    - bin/**/*

Documentation:
  # don't require classes to be documented
  Enabled: false

Encoding:
  # no need to always specify encoding
  Enabled: false

LineLength:
  # just one more character please
  Max: 80

Style/FileName:
  # ok to requre grape-markdown gem
  Enabled: false
